name: CI-GO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:
#   CHAVE: ${{ secrets.VALOR}} 

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go 1.21.x
      uses: actions/setup-go@v4
      with:
        # Semantic version range syntax or exact version of Go
        go-version: '1.21.x'
    
    - name: Display Go version
      run: go version

    - name: Run File
      run: go run hello-world.go
      
    - name: Build Binary
      run: go build -v hello-world.go
    
    - name: List Files
      run: ls -la

    - name: Run Binary
      run: ./hello-world
  
    # - name: eslint
    #   run: npm i && npm run lint
  
  # security:
  #   runs-on: ubuntu-20.04
  #   stepes:
  #   - uses: actions/checkout@master
  #   - name: Run Snyk node
  #     uses: synk/actions/node@master
  #     env:
  #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Gerado na conta do snyk
  #   - name: Run Snyk Go
  #       uses: snyk/actions/golang@master
  #       env: 
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Gerado na conta do snyk


